name: Deploy to Railway via CLI

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: 'Git Tag ที่ต้องการ deploy (เช่น v1.0.0)'
        required: true
        type: string

      app_env:
        description: 'Target Environment (SIT, UAT, PROD)'
        required: true
        type: choice
        options: [SIT, UAT, PROD]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.app_env }}

    steps:
      # -------------------------------
      # 1️ Checkout โค้ดจาก tag ที่เลือก
      # -------------------------------
      - name: Checkout code from tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.git_tag }}

      # -------------------------------
      # 2️ Set lowercase app_env
      # -------------------------------
      - name: Set lowercase app_env
        id: vars
        run: |
          ENV=$(echo "${{ github.event.inputs.app_env }}" | tr '[:upper:]' '[:lower:]')
          echo "APP_ENV=$ENV" >> $GITHUB_OUTPUT

      # -------------------------------
      # 3️ ตั้งค่า Railway Token และ Service ID จาก Secrets
      # -------------------------------
      - name: Set Railway environment variables
        run: |
          echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_API_TOKEN }}" >> $GITHUB_ENV
          echo "RAILWAY_SERVICE_ID=${{ secrets.RAILWAY_SERVICE_ID }}" >> $GITHUB_ENV

      # -------------------------------
      # 4️ ติดตั้ง Railway CLI
      # -------------------------------
      - name: Install Railway CLI
        run: |
          curl -sSL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | sh
          railway --version

      # -------------------------------
      # 5️ Deploy ผ่าน CLI (build จาก repo)
      # -------------------------------
      - name: Deploy to Railway
        run: |
          echo "Deploying project to Railway (CLI build from repo)..."
          railway deployment up \
            --service $RAILWAY_SERVICE_ID \
            --environment ${{ steps.vars.outputs.APP_ENV }} \
            --verbose
