name: Deploy to Railway via CLI

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: 'Git Tag ที่ต้องการ deploy (เช่น v1.0.0)'
        required: true
        type: string

      app_env:
        description: 'Target Environment (SIT, UAT, PROD)'
        required: true
        type: choice
        options: [SIT, UAT, PROD]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # GitHub จะดึง Environment secrets ตาม environment ที่เลือก
    environment: ${{ github.event.inputs.app_env }}

    steps:
      # -------------------------------
      # 1️ Checkout code ตาม Git tag
      # -------------------------------
      - name: Checkout code from tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.git_tag }}

      # -------------------------------
      # 2️ Set lowercase app_env output
      # -------------------------------
      - name: Set lowercase app_env
        id: vars
        run: |
          ENV=$(echo "${{ github.event.inputs.app_env }}" | tr '[:upper:]' '[:lower:]')
          echo "APP_ENV=$ENV" >> $GITHUB_OUTPUT

      # -------------------------------
      # 3️ Set Railway Token & Service ID from Environment secrets
      # -------------------------------
      - name: Set Railway environment variables
        run: |
          echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_API_TOKEN }}" >> $GITHUB_ENV
          echo "RAILWAY_SERVICE_ID=${{ secrets.RAILWAY_SERVICE_ID }}" >> $GITHUB_ENV

      # -------------------------------
      # 4️ Install Node dependencies
      # -------------------------------
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # -------------------------------
      # 5️ Build React app ตาม environment
      # -------------------------------
      - name: Build React app
        run: |
          if [ "${{ github.event.inputs.app_env }}" = "SIT" ]; then
            yarn build:sit
          elif [ "${{ github.event.inputs.app_env }}" = "UAT" ]; then
            yarn build:uat
          elif [ "${{ github.event.inputs.app_env }}" = "PROD" ]; then
            yarn build:prod
          fi

      # -------------------------------
      # 6️ Install Railway CLI
      # -------------------------------
      - name: Install Railway CLI
        run: |
          curl -sSL https://raw.githubusercontent.com/railwayapp/cli/master/install.sh | sh
          railway --version

      # -------------------------------
      # 7️ Deploy ผ่าน Railway CLI
      # -------------------------------
      - name: Deploy to Railway
        run: |
          echo "Deploying project to Railway Service ID $RAILWAY_SERVICE_ID..."
          railway deployment up \
            --service $RAILWAY_SERVICE_ID \
            --environment ${{ steps.vars.outputs.APP_ENV }} \
            --verbose \
            --detach
