name: Deploy Frontend to Railway

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: 'Git Tag ที่ต้องการ deploy (เช่น v1.0.0)'
        required: true
        type: string

      app_env:
        description: 'Target Environment (SIT, UAT, PROD)'
        required: true
        type: choice
        options: [SIT, UAT, PROD]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.app_env }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy .env file
        run: |
          case "${{ inputs.app_env }}" in
            SIT) cp .env.sit .env ;;
            UAT) cp .env.uat .env ;;
            PROD) cp .env.prod .env ;;
            *) echo "Unknown environment" && exit 1 ;;
          esac

      - name: Build Docker image
        run: docker build -t my-frontend:${{ inputs.app_env }} .

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: |
          echo "Deploying Frontend version ${{ inputs.git_tag }} to Railway..."
          railway login --ci --apiToken ${{ secrets.RAILWAY_WEB_SERVICE_TOKEN }}
          railway up --service frontend-${{ inputs.app_env }} --detach
